FROM resin/%%RESIN_MACHINE_NAME%%-debian:jessie

WORKDIR /usr/src/app/
ENV INITSYSTEM on

# python-dbus for dbus communication
# python-flash for example server
RUN apt-get update && \
    apt-get install -yq \
      python-dbus \
      python-flask

COPY *.py ./
COPY start.sh ./

CMD ["bash", "start.sh"]
