FROM resin/%%RESIN_MACHINE_NAME%%-debian:jessie

WORKDIR /usr/src/app/
ENV INITSYSTEM on

RUN apt-get update && apt-get install -yq python-dbus

COPY *.py ./
COPY start.sh ./

CMD ["bash", "start.sh"]
